#!/usr/bin/env bash
# displays Holberton School 10 times and other word

WORD=0
while [ $WORD -lt 11 ]
do
    if [ $WORD = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ((WORD+=1))
done
