#!/usr/bin/bash
#view content the file school

PHRASE="school"

if [ -e "$PHRASE" ]
then
    echo "school file exists"
    if [ ! -s "$PHRASE" ]
    then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi
    if [ -f "$PHRASE" ]
    then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
